//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristaFrontEnd.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouristaFrontEnd.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Core Values.
        /// </summary>
        public static string About_CoreValuesTitle {
            get {
                return ResourceManager.GetString("About_CoreValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Trading &amp; Real Estate Investment Ltd.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourista International Company.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are many variations of passages ,but the majority have suffered alteration in some form, by injected humour, or randomised words which don&apos;t look..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the hotel.
        /// </summary>
        public static string Aboutthehotel {
            get {
                return ResourceManager.GetString("Aboutthehotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach file Required.
        /// </summary>
        public static string Attach_file_Required {
            get {
                return ResourceManager.GetString("Attach_file_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWESOME TOURS.
        /// </summary>
        public static string AWESOMETOURS {
            get {
                return ResourceManager.GetString("AWESOMETOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big world.
        /// </summary>
        public static string bigworld {
            get {
                return ResourceManager.GetString("bigworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string Booking_Adults {
            get {
                return ResourceManager.GetString("Booking_Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in.
        /// </summary>
        public static string Booking_CheckIn {
            get {
                return ResourceManager.GetString("Booking_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out.
        /// </summary>
        public static string Booking_Checkout {
            get {
                return ResourceManager.GetString("Booking_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Booking_Child {
            get {
                return ResourceManager.GetString("Booking_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Your booking is Registered, one of our Reservation office will contact Shortly.
        /// </summary>
        public static string Booking_ConfirmMsg {
            get {
                return ResourceManager.GetString("Booking_ConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Booking_Create {
            get {
                return ResourceManager.GetString("Booking_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Details.
        /// </summary>
        public static string Booking_Details {
            get {
                return ResourceManager.GetString("Booking_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Booking_Email {
            get {
                return ResourceManager.GetString("Booking_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Booking_FirstName {
            get {
                return ResourceManager.GetString("Booking_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel .
        /// </summary>
        public static string Booking_HotelName {
            get {
                return ResourceManager.GetString("Booking_HotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Check-in Date.
        /// </summary>
        public static string Booking_JS1 {
            get {
                return ResourceManager.GetString("Booking_JS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Check-out Date.
        /// </summary>
        public static string Booking_JS2 {
            get {
                return ResourceManager.GetString("Booking_JS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Adult.
        /// </summary>
        public static string Booking_JS3 {
            get {
                return ResourceManager.GetString("Booking_JS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Child.
        /// </summary>
        public static string Booking_JS4 {
            get {
                return ResourceManager.GetString("Booking_JS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Booking_LastName {
            get {
                return ResourceManager.GetString("Booking_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Booking_Mobile {
            get {
                return ResourceManager.GetString("Booking_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string Booking_PageTitle {
            get {
                return ResourceManager.GetString("Booking_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string Booking_Personalinfo {
            get {
                return ResourceManager.GetString("Booking_Personalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Reservation ID .
        /// </summary>
        public static string Booking_ReservationID {
            get {
                return ResourceManager.GetString("Booking_ReservationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        public static string Booking_ThankYou {
            get {
                return ResourceManager.GetString("Booking_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach C.V.
        /// </summary>
        public static string Career_Details_Attach {
            get {
                return ResourceManager.GetString("Career_Details_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Career_Details_Create {
            get {
                return ResourceManager.GetString("Career_Details_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality and Administartion.
        /// </summary>
        public static string Career_Details_Description {
            get {
                return ResourceManager.GetString("Career_Details_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Career_Details_Email {
            get {
                return ResourceManager.GetString("Career_Details_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Career_Details_Firstname {
            get {
                return ResourceManager.GetString("Career_Details_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload PDF or Doc.
        /// </summary>
        public static string Career_Details_JS_Alert {
            get {
                return ResourceManager.GetString("Career_Details_JS_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Career_Details_LastName {
            get {
                return ResourceManager.GetString("Career_Details_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Career_Details_Message {
            get {
                return ResourceManager.GetString("Career_Details_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        public static string Career_Details_PhoneNo {
            get {
                return ResourceManager.GetString("Career_Details_PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postion Details.
        /// </summary>
        public static string Career_Details_PositionTitle {
            get {
                return ResourceManager.GetString("Career_Details_PositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string Career_Details_Title {
            get {
                return ResourceManager.GetString("Career_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to this Job.
        /// </summary>
        public static string Career_Index_Apply_Button {
            get {
                return ResourceManager.GetString("Career_Index_Apply_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality and Administartion.
        /// </summary>
        public static string Career_Index_Desc {
            get {
                return ResourceManager.GetString("Career_Index_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Career_Index_Job_Desc {
            get {
                return ResourceManager.GetString("Career_Index_Job_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        public static string Career_Index_Job_Education {
            get {
                return ResourceManager.GetString("Career_Index_Job_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Career_Index_Job_Exp {
            get {
                return ResourceManager.GetString("Career_Index_Job_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Level.
        /// </summary>
        public static string Career_Index_Job_Level {
            get {
                return ResourceManager.GetString("Career_Index_Job_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Career_Index_Job_Requirements {
            get {
                return ResourceManager.GetString("Career_Index_Job_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string Career_Index_Job_Type {
            get {
                return ResourceManager.GetString("Career_Index_Job_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancies.
        /// </summary>
        public static string Career_Index_Job_Vacancies {
            get {
                return ResourceManager.GetString("Career_Index_Job_Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOB OPENNINGS.
        /// </summary>
        public static string Career_Index_Title {
            get {
                return ResourceManager.GetString("Career_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string clickherer {
            get {
                return ResourceManager.GetString("clickherer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ContactUs_Email {
            get {
                return ResourceManager.GetString("ContactUs_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check Email.
        /// </summary>
        public static string ContactUs_Email_Val {
            get {
                return ResourceManager.GetString("ContactUs_Email_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter First Name.
        /// </summary>
        public static string ContactUs_Firstname_Val {
            get {
                return ResourceManager.GetString("ContactUs_Firstname_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string ContactUs_FullName {
            get {
                return ResourceManager.GetString("ContactUs_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending...
        /// </summary>
        public static string ContactUs_JS_1 {
            get {
                return ResourceManager.GetString("ContactUs_JS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Submitted , Thank you !.
        /// </summary>
        public static string ContactUs_JS_2 {
            get {
                return ResourceManager.GetString("ContactUs_JS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ContactUs_Message {
            get {
                return ResourceManager.GetString("ContactUs_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Message.
        /// </summary>
        public static string ContactUs_Message_Val {
            get {
                return ResourceManager.GetString("ContactUs_Message_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ContactUs_Phone {
            get {
                return ResourceManager.GetString("ContactUs_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Phone.
        /// </summary>
        public static string ContactUs_Phone_Val {
            get {
                return ResourceManager.GetString("ContactUs_Phone_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ContactUs_SendButton {
            get {
                return ResourceManager.GetString("ContactUs_SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an inquiry.
        /// </summary>
        public static string ContactUs_SendInquiry {
            get {
                return ResourceManager.GetString("ContactUs_SendInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just pack and go! Let leave your travel plan to travel experts!.
        /// </summary>
        public static string Contactus_Text {
            get {
                return ResourceManager.GetString("Contactus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs_Title {
            get {
                return ResourceManager.GetString("ContactUs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Address.
        /// </summary>
        public static string CotactUs_OfficeAddress {
            get {
                return ResourceManager.GetString("CotactUs_OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discover.
        /// </summary>
        public static string discover {
            get {
                return ResourceManager.GetString("discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The world you have never seen.
        /// </summary>
        public static string discovertext {
            get {
                return ResourceManager.GetString("discovertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Are Facing Some issues , Please Check Back Later.
        /// </summary>
        public static string ErrorPage_Desc {
            get {
                return ResourceManager.GetString("ErrorPage_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,Page your Are Looking For Doesn&apos;t Exist Or Site Currently Under Maintenance.
        /// </summary>
        public static string ErrorPage_Title {
            get {
                return ResourceManager.GetString("ErrorPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURED HOTELS.
        /// </summary>
        public static string FEATUREDHOTELS {
            get {
                return ResourceManager.GetString("FEATUREDHOTELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND HOTEL.
        /// </summary>
        public static string FINDHOTEL {
            get {
                return ResourceManager.GetString("FINDHOTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required.
        /// </summary>
        public static string First_Name_Required {
            get {
                return ResourceManager.GetString("First_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLIGHT.
        /// </summary>
        public static string FLIGHT {
            get {
                return ResourceManager.GetString("FLIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Footer_ContactUs {
            get {
                return ResourceManager.GetString("Footer_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2017 GMG Technology Group . All rights reserved..
        /// </summary>
        public static string Footer_CopyRights {
            get {
                return ResourceManager.GetString("Footer_CopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailBox.
        /// </summary>
        public static string Footer_Mailbox {
            get {
                return ResourceManager.GetString("Footer_Mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsLetter.
        /// </summary>
        public static string Footer_Newsletter {
            get {
                return ResourceManager.GetString("Footer_Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email Already Exist.
        /// </summary>
        public static string Footer_NewsletterAlreadyExist {
            get {
                return ResourceManager.GetString("Footer_NewsletterAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string Footer_NewsletterBoxEmail {
            get {
                return ResourceManager.GetString("Footer_NewsletterBoxEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Footer_NewsletterButton {
            get {
                return ResourceManager.GetString("Footer_NewsletterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to Our Newsletter.
        /// </summary>
        public static string Footer_NewsletterDesc {
            get {
                return ResourceManager.GetString("Footer_NewsletterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct email format.
        /// </summary>
        public static string Footer_NewsletterError {
            get {
                return ResourceManager.GetString("Footer_NewsletterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        public static string Footer_NewsletterSending {
            get {
                return ResourceManager.GetString("Footer_NewsletterSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Submitted , Thank you !.
        /// </summary>
        public static string Footer_NewsletterSubmitMsg {
            get {
                return ResourceManager.GetString("Footer_NewsletterSubmitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code .
        /// </summary>
        public static string Footer_PostalCode {
            get {
                return ResourceManager.GetString("Footer_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string Footer_SocialMedia {
            get {
                return ResourceManager.GetString("Footer_SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Footer_Twitter {
            get {
                return ResourceManager.GetString("Footer_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO EXPLORE.
        /// </summary>
        public static string GOEXPLORE {
            get {
                return ResourceManager.GetString("GOEXPLORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Header_About {
            get {
                return ResourceManager.GetString("Header_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string Header_Careers {
            get {
                return ResourceManager.GetString("Header_Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Header_Contact {
            get {
                return ResourceManager.GetString("Header_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Header_Home {
            get {
                return ResourceManager.GetString("Header_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        public static string Header_Hotels {
            get {
                return ResourceManager.GetString("Header_Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Header_Languages {
            get {
                return ResourceManager.GetString("Header_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Attractions.
        /// </summary>
        public static string Header_News {
            get {
                return ResourceManager.GetString("Header_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Header_Offers {
            get {
                return ResourceManager.GetString("Header_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership.
        /// </summary>
        public static string Header_Owners {
            get {
                return ResourceManager.GetString("Header_Owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These best rooms chosen by our customers.
        /// </summary>
        public static string Home_HotelFacilitiesDesc {
            get {
                return ResourceManager.GetString("Home_HotelFacilitiesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOTEL FACILTIES.
        /// </summary>
        public static string Home_HotelFacilitiesTitle {
            get {
                return ResourceManager.GetString("Home_HotelFacilitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR GALLERY.
        /// </summary>
        public static string Home_OurGallery {
            get {
                return ResourceManager.GetString("Home_OurGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These best rooms chosen by our customers.
        /// </summary>
        public static string Home_OurHotelsDesc {
            get {
                return ResourceManager.GetString("Home_OurHotelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR BEST ROOMS.
        /// </summary>
        public static string Home_OurHotelsTitle {
            get {
                return ResourceManager.GetString("Home_OurHotelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the Visionary Minds Behind our Success.
        /// </summary>
        public static string Home_OwnersDesc {
            get {
                return ResourceManager.GetString("Home_OwnersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEADERSHIP.
        /// </summary>
        public static string Home_OwnersTitle {
            get {
                return ResourceManager.GetString("Home_OwnersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT NEWS.
        /// </summary>
        public static string Home_RecentNews {
            get {
                return ResourceManager.GetString("Home_RecentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string Home_SearchRoomsAdult {
            get {
                return ResourceManager.GetString("Home_SearchRoomsAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Now.
        /// </summary>
        public static string Home_SearchRoomsButton {
            get {
                return ResourceManager.GetString("Home_SearchRoomsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string Home_SearchRoomsCheckin {
            get {
                return ResourceManager.GetString("Home_SearchRoomsCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string Home_SearchRoomsCheckout {
            get {
                return ResourceManager.GetString("Home_SearchRoomsCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Home_SearchRoomsChild {
            get {
                return ResourceManager.GetString("Home_SearchRoomsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR RATES &amp; AVAILABILITY.
        /// </summary>
        public static string Home_SearchRoomsDesc {
            get {
                return ResourceManager.GetString("Home_SearchRoomsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH ROOMS.
        /// </summary>
        public static string Home_SearchRoomsTitle {
            get {
                return ResourceManager.GetString("Home_SearchRoomsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string Hotel_Details_CheckIn {
            get {
                return ResourceManager.GetString("Hotel_Details_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string Hotel_Details_Checkout {
            get {
                return ResourceManager.GetString("Hotel_Details_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Hotel_Details_Description {
            get {
                return ResourceManager.GetString("Hotel_Details_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        public static string Hotel_Details_Facilities {
            get {
                return ResourceManager.GetString("Hotel_Details_Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string Hotel_Index_Button_Details {
            get {
                return ResourceManager.GetString("Hotel_Index_Button_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxury And Spacious.
        /// </summary>
        public static string Hotel_Index_Desc {
            get {
                return ResourceManager.GetString("Hotel_Index_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Hotels.
        /// </summary>
        public static string Hotel_Index_Title {
            get {
                return ResourceManager.GetString("Hotel_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Hotel_Night {
            get {
                return ResourceManager.GetString("Hotel_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Overview.
        /// </summary>
        public static string HotelOverview {
            get {
                return ResourceManager.GetString("HotelOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT’S A.
        /// </summary>
        public static string its {
            get {
                return ResourceManager.GetString("its", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required.
        /// </summary>
        public static string Last_Name_Required {
            get {
                return ResourceManager.GetString("Last_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Tourist Attractions.
        /// </summary>
        public static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Hotel.
        /// </summary>
        public static string MoreHotel {
            get {
                return ResourceManager.GetString("MoreHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more tours.
        /// </summary>
        public static string moretours {
            get {
                return ResourceManager.GetString("moretours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string News_Category {
            get {
                return ResourceManager.GetString("News_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Tourist Attractions.
        /// </summary>
        public static string News_Index_Desc {
            get {
                return ResourceManager.GetString("News_Index_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Reading.
        /// </summary>
        public static string News_Index_Details {
            get {
                return ResourceManager.GetString("News_Index_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tourist Attractions.
        /// </summary>
        public static string News_Index_Title {
            get {
                return ResourceManager.GetString("News_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Tourist Attractions.
        /// </summary>
        public static string News_RecentNews {
            get {
                return ResourceManager.GetString("News_RecentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfRoom Required.
        /// </summary>
        public static string NumberOfRoom_Required {
            get {
                return ResourceManager.GetString("NumberOfRoom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Offers Available.
        /// </summary>
        public static string Offers_Error {
            get {
                return ResourceManager.GetString("Offers_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Offers.
        /// </summary>
        public static string Offers_Index_Desc {
            get {
                return ResourceManager.GetString("Offers_Index_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string Offers_Index_Details {
            get {
                return ResourceManager.GetString("Offers_Index_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Offers.
        /// </summary>
        public static string Offers_Index_Title {
            get {
                return ResourceManager.GetString("Offers_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our organization.
        /// </summary>
        public static string Ourorganization {
            get {
                return ResourceManager.GetString("Ourorganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT THERE.
        /// </summary>
        public static string outthere {
            get {
                return ResourceManager.GetString("outthere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the Visionary Minds Behind our Success.
        /// </summary>
        public static string Owners_Desc {
            get {
                return ResourceManager.GetString("Owners_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Team.
        /// </summary>
        public static string Owners_SuccessTeam {
            get {
                return ResourceManager.GetString("Owners_SuccessTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership.
        /// </summary>
        public static string Owners_Title {
            get {
                return ResourceManager.GetString("Owners_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACK AND GO.
        /// </summary>
        public static string PACK {
            get {
                return ResourceManager.GetString("PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNo Required.
        /// </summary>
        public static string PhoneNo_Required {
            get {
                return ResourceManager.GetString("PhoneNo_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related.
        /// </summary>
        public static string Related {
            get {
                return ResourceManager.GetString("Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Keyword....
        /// </summary>
        public static string Search_Box {
            get {
                return ResourceManager.GetString("Search_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all of your Search results.
        /// </summary>
        public static string Search_Desc {
            get {
                return ResourceManager.GetString("Search_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string Search_Label {
            get {
                return ResourceManager.GetString("Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/layout.css.
        /// </summary>
        public static string StyleUrl {
            get {
                return ResourceManager.GetString("StyleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/components.css.
        /// </summary>
        public static string StyleUrl2 {
            get {
                return ResourceManager.GetString("StyleUrl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        public static string Tours {
            get {
                return ResourceManager.GetString("Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Tours.
        /// </summary>
        public static string viewtours {
            get {
                return ResourceManager.GetString("viewtours", resourceCulture);
            }
        }
    }
}
